export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST"
export const REMOVE_FROM_MY_LIST = "REMOVE_FROM_MY_LIST"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_INIT = "GET_MOVIES_INIT"